server:
  port: ${API_GATEWAY_SERVER_PORT}

spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://${ZIPKIN_SERVER_HOST}:${ZIPKIN_SERVER_PORT}
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: false
      routes:
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/v1/customers/**

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER_HOST}:${EUREKA_SERVER_PORT}/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: false
    hostname: ${API_GATEWAY_SERVER_HOST}