server:
  port: ${CUSTOMER_SERVER_PORT}

spring:
  application:
    name: customer-service
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_SERVER_HOST}:${DB_SERVER_PORT}/customer
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  zipkin:
    base-url: http://${ZIPKIN_SERVER_HOST}:${ZIPKIN_SERVER_PORT}
  rabbitmq:
    addresses: ${RABBITMQ_HOST}:${RABBITMQ_PORT}

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER_HOST}:${EUREKA_SERVER_PORT}/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: false
  instance:
    prefer-ip-address: false
    hostname: ${CUSTOMER_SERVER_HOST}