server:
  port: ${EUREKA_SERVER_PORT}

spring:
  application:
    name: eureka-server
  zipkin:
    base-url: http://${ZIPKIN_SERVER_HOST}:${ZIPKIN_SERVER_PORT}

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER_HOST}:${EUREKA_SERVER_PORT}/eureka
    fetch-registry: false
    register-with-eureka: false